### ISSUE TITLE
Error Log Issue

### ISSUE THREAD

**Issue by HenioH** [LuciferOnKodi/repository.lucifer#1]
Whenever a movie is selected in Strictly HD then it starts to scrape an error log pops up during scrapping then goes back to movie title page. This started happening today prior to today was working flawless.

**Comment by LuciferOnKodi** [comment]
Ok..... well you need to provide an error log for me to diagnose an issue.

**Comment by HenioH** [comment]
Here you go: https://pastebin.com/raw/gXeUd7p7

**Comment by LuciferOnKodi** [comment]
Thanks for the log. It's odd because no one else has reported this issue and it should be _**very** _ noticeable. The addon shouldn't be usable for anyone if this were a true error. The only thing I can suggest is uninstall, then reinstall. Might have just went corrupt somehow.

**Comment by Beechnut1** [comment]
Lucifer I'm Loving your addon as well. I too am getting the same error. Log coming,

**Comment by HenioH** [comment]
I Uninstalled then reinstalled with same issue. I also installed a blank Kodi 17.5 then the Lucifer Repo. Installed Strictly HD with same results with nothing else installed in my Kodi.

**Comment by LuciferOnKodi** [comment]
Are both of you on 17.5? Try 17.4 or lower

**Comment by Beechnut1** [comment]
17.5

**Comment by LuciferOnKodi** [comment]
That's likely the issue. Downgrade to 17.1-17.4

**Comment by LuciferOnKodi** [comment]
Will need to look into 17.5 changes as it's apparently causing errors in the way the addon is coded.

**Comment by HenioH** [comment]
Dont know what it could be same error on 17.4

**Comment by LuciferOnKodi** [comment]
I know the issue. Will push a fix Monday.

**Comment by HenioH** [comment]
Awesome. Thank you for your hardwork! best links out there!
